FROM --platform=$BUILDPLATFORM golang:1.25-alpine AS build
ARG TARGETOS
ARG TARGETARCH
WORKDIR /src
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -o /out/fugue-controller ./cmd/fugue-controller

FROM --platform=$TARGETPLATFORM golang:1.25-alpine
RUN apk add --no-cache bash ca-certificates curl git kubectl
WORKDIR /app
COPY --from=build /out/fugue-controller /usr/local/bin/fugue-controller
ENTRYPOINT ["/usr/local/bin/fugue-controller"]
