{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fugue.controllerDeploymentName" . }}-cold-state
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fugue.controllerDeploymentName" . }}-cold-state
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fugue.controllerDeploymentName" . }}-cold-state
subjects:
  - kind: ServiceAccount
    name: {{ include "fugue.controlPlaneServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
