{{- if .Values.headscale.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fugue.headscaleServiceName" . }}
  labels:
    {{- include "fugue.componentLabels" (dict "root" . "component" "headscale") | nindent 4 }}
spec:
  type: {{ .Values.headscale.service.type }}
  selector:
    {{- include "fugue.componentSelectorLabels" (dict "root" . "component" "headscale") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.headscale.service.port }}
      targetPort: {{ .Values.headscale.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.headscale.service.type "NodePort") .Values.headscale.service.nodePort }}
      nodePort: {{ .Values.headscale.service.nodePort }}
      {{- end }}
{{- end }}
