{{- $apiPDB := default (dict) .Values.api.podDisruptionBudget -}}
{{- $controllerPDB := default (dict) .Values.controller.podDisruptionBudget -}}
{{- if and (default false (get $apiPDB "enabled")) (gt (int .Values.api.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fugue.apiDeploymentName" . }}
  labels:
    {{- include "fugue.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  minAvailable: {{ default 1 (get $apiPDB "minAvailable") }}
  selector:
    matchLabels:
      {{- include "fugue.componentSelectorLabels" (dict "root" . "component" "api") | nindent 6 }}
{{- end }}
{{- if and (default false (get $controllerPDB "enabled")) (gt (int .Values.controller.replicaCount) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fugue.controllerDeploymentName" . }}
  labels:
    {{- include "fugue.componentLabels" (dict "root" . "component" "controller") | nindent 4 }}
spec:
  minAvailable: {{ default 1 (get $controllerPDB "minAvailable") }}
  selector:
    matchLabels:
      {{- include "fugue.componentSelectorLabels" (dict "root" . "component" "controller") | nindent 6 }}
{{- end }}
