{{- $registry := (.Values.registry | default (dict)) -}}
{{- $registryPersistence := (get $registry "persistence" | default (dict)) -}}
{{- $registryPersistenceMode := "pvc" -}}
{{- if hasKey $registryPersistence "mode" -}}
{{- $registryPersistenceMode = (get $registryPersistence "mode") -}}
{{- end -}}
{{- $movableRWOStorage := (get .Values "movableRWOStorage" | default (dict)) -}}
{{- $registryStorageClassName := "" -}}
{{- if hasKey $registryPersistence "storageClassName" -}}
{{- $registryStorageClassName = (get $registryPersistence "storageClassName" | default "") -}}
{{- end -}}
{{- if eq (trim $registryStorageClassName) "" -}}
{{- $registryStorageClassName = (get $movableRWOStorage "storageClassName" | default "") -}}
{{- end -}}
{{- if and .Values.registry.enabled (eq $registryPersistenceMode "pvc") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fugue.fullname" . }}-registry-data
  labels:
    {{- include "fugue.componentLabels" (dict "root" . "component" "registry") | nindent 4 }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" (get $registryPersistence "accessMode") }}
  resources:
    requests:
      storage: {{ default "50Gi" (get $registryPersistence "size") }}
  {{- if $registryStorageClassName }}
  storageClassName: {{ $registryStorageClassName | quote }}
  {{- end }}
{{- end }}
