{{- $secretName := include "fugue.configSecretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $bootstrapAdminKey := .Values.bootstrapAdminKey -}}
{{- if and (eq $bootstrapAdminKey "") $existingSecret -}}
  {{- $bootstrapAdminKey = (index $existingSecret.data "FUGUE_BOOTSTRAP_ADMIN_KEY" | b64dec) -}}
{{- end -}}
{{- if eq $bootstrapAdminKey "" -}}
  {{- $bootstrapAdminKey = "fugue_bootstrap_admin_change_me" -}}
{{- end -}}
{{- $postgresPassword := .Values.postgres.password -}}
{{- if and (eq $postgresPassword "") $existingSecret -}}
  {{- $existingPostgresPassword := index $existingSecret.data "POSTGRES_PASSWORD" -}}
  {{- if $existingPostgresPassword -}}
    {{- $postgresPassword = ($existingPostgresPassword | b64dec) -}}
  {{- end -}}
{{- end -}}
{{- if and .Values.postgres.enabled (eq $postgresPassword "") -}}
  {{- $postgresPassword = randAlphaNum 32 -}}
{{- end -}}
{{- $databaseURL := .Values.api.databaseURL -}}
{{- if eq $databaseURL "" -}}
  {{- if .Values.postgres.enabled -}}
    {{- $databaseURL = printf "postgres://%s:%s@%s:%v/%s?sslmode=disable" .Values.postgres.username $postgresPassword (include "fugue.postgresServiceName" .) .Values.postgres.service.port .Values.postgres.database -}}
  {{- else -}}
    {{- fail "api.databaseURL must be set when postgres.enabled=false" -}}
  {{- end -}}
{{- end -}}
{{- $clusterJoinToken := .Values.api.clusterJoinToken -}}
{{- if and (eq $clusterJoinToken "") $existingSecret -}}
  {{- $existingClusterJoinToken := index $existingSecret.data "FUGUE_CLUSTER_JOIN_TOKEN" -}}
  {{- if $existingClusterJoinToken -}}
    {{- $clusterJoinToken = ($existingClusterJoinToken | b64dec) -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "fugue.labels" . | nindent 4 }}
type: Opaque
stringData:
  FUGUE_BOOTSTRAP_ADMIN_KEY: {{ $bootstrapAdminKey | quote }}
  FUGUE_DATABASE_URL: {{ $databaseURL | quote }}
  FUGUE_CLUSTER_JOIN_SERVER: {{ .Values.api.clusterJoinServer | quote }}
  FUGUE_CLUSTER_JOIN_TOKEN: {{ $clusterJoinToken | quote }}
  POSTGRES_PASSWORD: {{ $postgresPassword | quote }}
