apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fugue.fullname" . }}-config
  labels:
    {{- include "fugue.labels" . | nindent 4 }}
type: Opaque
stringData:
  FUGUE_BOOTSTRAP_ADMIN_KEY: {{ .Values.bootstrapAdminKey | quote }}
