apiVersion: v1
kind: Service
metadata:
  name: {{ include "fugue.fullname" . }}
  labels:
    {{- include "fugue.componentLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "fugue.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
