package store

import (
	"context"
	"strings"
	"time"

	"fugue/internal/model"
)

// GetTenantBillingSummaries accrues each distinct tenant once and returns the
// complete result only after every ledger and counterparty credit is committed.
func (s *Store) GetTenantBillingSummaries(ctx context.Context, tenantIDs []string) ([]model.TenantBillingSummary, []string, error) {
	snapshot, err := s.GetTenantBillingSnapshot(ctx, tenantIDs)
	return snapshot.Billings, snapshot.MissingTenantIDs, err
}

// TenantBillingSnapshot contains the complete ledger result and its resource
// inputs for an API usage overlay. It is internal store data, not an HTTP body.
type TenantBillingSnapshot struct {
	Billings         []model.TenantBillingSummary
	MissingTenantIDs []string
	Apps             []model.App
	Runtimes         []model.Runtime
}

func (s *Store) GetTenantBillingSnapshot(ctx context.Context, tenantIDs []string) (TenantBillingSnapshot, error) {
	ids := make([]string, 0, len(tenantIDs))
	seen := make(map[string]bool, len(tenantIDs))
	for _, raw := range tenantIDs {
		id := strings.TrimSpace(raw)
		if id == "" {
			return TenantBillingSnapshot{}, ErrInvalidInput
		}
		if !seen[id] {
			seen[id] = true
			ids = append(ids, id)
		}
	}
	if len(ids) == 0 || len(ids) > 500 {
		return TenantBillingSnapshot{}, ErrInvalidInput
	}
	if s.usingDatabase() {
		return s.pgGetTenantBillingSnapshot(ctx, ids)
	}
	var snapshot TenantBillingSnapshot
	err := s.withLockedState(true, func(state *model.State) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		summaries, missing := accrueBillingSummaries(state, ids, time.Now().UTC())
		snapshot = completeTenantBillingSnapshot(state, ids, summaries, missing)
		return nil
	})
	return snapshot, err
}

func completeTenantBillingSnapshot(state *model.State, ids []string, summaries []model.TenantBillingSummary, missing []string) TenantBillingSnapshot {
	selected := make(map[string]bool, len(ids))
	for _, id := range ids {
		selected[id] = true
	}
	result := TenantBillingSnapshot{Billings: summaries, MissingTenantIDs: missing, Runtimes: state.Runtimes}
	index := newAppBackingServiceIndex(state)
	for _, app := range state.Apps {
		if !selected[app.TenantID] {
			continue
		}
		normalizeAppStatusForRead(&app)
		if isDeletedApp(app) {
			continue
		}
		hydrateAppBackingServicesWithIndex(index, &app)
		result.Apps = append(result.Apps, app)
	}
	return result
}

func accrueBillingSummaries(state *model.State, ids []string, now time.Time) ([]model.TenantBillingSummary, []string) {
	index := newBillingStateIndex(state)
	present := make(map[string]bool, len(state.Tenants))
	for _, tenant := range state.Tenants {
		present[tenant.ID] = true
	}
	missing := make([]string, 0)
	for _, id := range ids {
		if !present[id] {
			missing = append(missing, id)
			continue
		}
		accrueTenantBillingLedgerWithIndex(state, index, id, now)
	}
	// Build after all accruals so a requested runtime owner includes credits
	// generated by other tenants in the same transaction, regardless of order.
	result := make([]model.TenantBillingSummary, 0, len(ids)-len(missing))
	for _, id := range ids {
		if present[id] {
			record := state.TenantBilling[findTenantBillingRecord(state, id)]
			result = append(result, buildTenantBillingSummaryWithIndex(state, index, record))
		}
	}
	return result, missing
}
